### ISSUE TITLE
`fisher install gh` doesn't make gh available as command?

### ISSUE THREAD

**Issue by cmdcolin** [dickeyxxx/gh#10]
I am using fisherman (https://github.com/fisherman/fisherman) and used `fisher install dickeyxxx/gh` but it still gives unknown command

    gh
    fish: Unknown command 'gh'

I noted that there were install instructions in the readme but is it possible to make this plugin installation via fisherman work?

**Comment by dickeyxxx** [comment]
Not familiar with fisherman, let me take a look and see what I can find.

**Comment by dickeyxxx** [comment]
Try it now.

**Comment by cmdcolin** [comment]
Seems to work now. Thanks!
