### ISSUE TITLE
Install gh for zsh/prezto

### ISSUE THREAD

**Issue by kopiczko** [dickeyxxx/gh#24]
Hi, I'm using https://github.com/sorin-ionescu/prezto, oh-my-zsh alternative. Is there a way to integrate gh not necessarily with prezto but zsh directly? I know I can use gh.bash, but I'd like to have completion enabled.

**Comment by dickeyxxx** [comment]
I have no idea, I'm not a zsh user.

**Comment by glor** [comment]
You can use the bash scripts. Zsh (at least newer versions) supports bash autocomplete.
It works with plain zsh so it should work with prezto. But you need to have compinit loaded first, then you can do:
```
# bash completion and gh
autoload bashcompinit
bashcompinit
source ~/src/github.com/dickeyxxx/gh/bash/gh.bash
source ~/src/github.com/dickeyxxx/gh/completions/gh.bash
```
