### ISSUE TITLE
Conflict with oh-my-zsh `gh` alias

### ISSUE THREAD

**Issue by jamesshedden** [dickeyxxx/gh#25]
Hey, I love `gh`, thanks so much!

I updated oh-my-zsh today and immediately afterwards found that I could only use `gh` as the `git help` oh-my-zsh alias. I pulled down the latest version of `dickeyxxx/gh` which didn't seem to have any effect so I then removed `gh` and reverted any other setup steps from your Readme, which I then went through again from scratch, also to no avail.

I might be being stupid but I can only get the previous behaviour working again by running `unalias gh`.

Thought I'd mention here — thanks again for the awesome productivity-enhancing tool! 😍

**Comment by patrick96** [comment]
This was actually changed back again [here](https://github.com/robbyrussell/oh-my-zsh/commit/76821f506c5f252b9542c1d168e6f30874e5c68d)
